<a href="https://colab.research.google.com/github/yashgovind/100xDevs-Cohort3-WebDev-and-Devops/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#create a array using numpy
# create a 1d array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [4]:
#converted into a 2-d array
arr2 = np.array([1,2,3,4,5])
print(arr2.reshape(1,5))

[[1 2 3 4 5]]


In [5]:
arr2 = np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]]) #2-d array
print(arr2)
print(arr2.shape) #2 rows 5 col

In [17]:
#creating arrays using inbuilt functions
np.arange(0,10,2) #(start,end,step)
#reshaping into 2d
np.arange(0,10,2).reshape(1,5)
# np.arange(0,10,2).reshape(5,1)

array([[0, 2, 4, 6, 8]])

In [19]:
#creating array using prebuilt functions
np.ones((3,4)) #creates an array of ones with 3 rows and 4 columns

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
#identity matrix  diagonals is 1.
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
#attributes of numpy array
arr = np.array([[1,2,3],[4,5,6]])

print('array:\n',arr)
print('array shape:\n',arr.shape)
print('array dimensions:\n',arr.ndim)
print('array size(no of ele):\n',arr.size)
print('array datatype:\n',arr.dtype)
print('array items size(in bytes):\n',arr.itemsize)


array:
 [[1 2 3]
 [4 5 6]]
array shape:
 (2, 3)
array dimensions:
 2
array size(no of ele):
 6
array datatype:
 int64
array items size(in bytes):
 8


In [24]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

#element wise addition

print("addition:",arr1+arr2)# each ele add itself
print("subtraction:",arr1-arr2)# each ele sub itself
print("multiplication:",arr1*arr2)# each ele mul itself
print("division:",arr1/arr2)# each ele div itself

addition: [11 22 33 44 55]
subtraction: [ -9 -18 -27 -36 -45]
multiplication: [ 10  40  90 160 250]
division: [0.1 0.1 0.1 0.1 0.1]


In [26]:
#Universal functions
arr = np.array([1,2,3,4,5,6])
#square root
print(np.sqrt(arr)) #square root of each element is being performed

#exponential
print(np.exp(arr)) #exponential of each ele


#sine
print(np.sin(arr))

#natural log
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [34]:
#array slicing and Indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n",arr)
# arr[0][0] #1 is printed.

# print(arr[1:,2:]) # we need 7,8,11,12 -> excercise-01
# print(arr[0:2 , 2:]) #we need 3,4,7,8
#we need 6,7,10,11
# print(arr[1:,1:3])

#modifying the array elements
arr[0,0] = 100
print(arr); #first ele is modified.

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [35]:
#Statistical Concept-Normalization
#To have a mean of 0 and SD of 1

data = np.array([1,2,3,4,5])

# mean and sd calculation
mean = np.mean(data)
std_dev = np.std(data)

#normalized data
normalized_data = (data - mean) / std_dev

print("Normalized Data:",normalized_data)

Normalized Data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [ ]:
#Statistical Concepts MORE-Pt-02

data = np.array([1,2,3,4,5])
#mean
mean = np.mean(data)
print("mean is:",mean)

#median
median = np.median(data)
print("median is :",median)

#standard deviation
std_dev = np.std(data)
print('Standard deviation is : ',std_dev)

#variance
variance = np.var(data)
print('Variance is : ',variance)

In [38]:
#Logical Operations
data = np.array([1,2,3,4,5,6,7,8,9,10])

data>5

data[data>5]

array([ 6,  7,  8,  9, 10])